allowBuilds:
  esbuild: true
  sharp: true

overrides:
  shiki: 4.3.0

minimumReleaseAgeExclude:
  - '@tailwindcss/node@4.3.2'
  - '@tailwindcss/oxide-android-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-x64@4.3.2'
  - '@tailwindcss/oxide-freebsd-x64@4.3.2'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.2'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.2'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.2'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.2'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.2'
  - '@tailwindcss/oxide@4.3.2'
  - '@tailwindcss/postcss@4.3.2'
  - fumadocs-core@16.10.7 || 16.14.3
  - fumadocs-ui@16.10.7 || 16.14.3
  - tailwindcss@4.3.2
  - hoshimi@0.5.0 || 0.5.2 || 0.5.3 || 0.5.5
  - fumadocs-mdx@15.2.3
  - lucide-react@1.31.0
  - '@biomejs/biome@2.5.9'
  - '@biomejs/cli-darwin-arm64@2.5.9'
  - '@biomejs/cli-darwin-x64@2.5.9'
  - '@biomejs/cli-linux-arm64-musl@2.5.9'
  - '@biomejs/cli-linux-arm64@2.5.9'
  - '@biomejs/cli-linux-x64-musl@2.5.9'
  - '@biomejs/cli-linux-x64@2.5.9'
  - '@biomejs/cli-win32-arm64@2.5.9'
  - '@biomejs/cli-win32-x64@2.5.9'

packages: []
